### ISSUE TITLE
client authentication issue with SSH

### ISSUE THREAD

**Issue by gosusnkr** [rsmusllp/king-phisher#429]
I have an issue, while getting authenticated into client with SSH, I used king phisher earlier, but this time only I'm facing issue, I'm using AWS kali, which is 2020.1, by default king-phisher is installed on this version of kali. I have 3 users in this machine, including root, and tried all 3 users credentials simultaneously, but no luck. Somebody help me on this.

**Comment by wolfthefallen** [comment]
For more infomration on Authentication please visit the wiki page [user-authentication](https://github.com/securestate/king-phisher/wiki/Server-Authentication#user-authentication).

With what ever user you are authenticating with the need to be able to login with ssh, if you are using SSH keys make sure the users `ssh-agent` is running and their ssh key has been added to it.

**Comment by gosusnkr** [comment]
I'm not using any ssh-keys for authentication, took RDP from xrdp service with new user(kali, credentials based auth).

Earlier it used work fine by providing logged in used credentials for ssh auth, this time not able.

**Comment by wolfthefallen** [comment]
I need more information on what error you are getting beyond "It's not working".. The username and password is the same as the username and password to ssh into the server. If you can provide the exact error you are getting and verify on the server end a connect is being made to ssh that would help too.

**Comment by gosusnkr** [comment]
![king-phisher error](https://user-images.githubusercontent.com/10269103/77822253-6406cb80-710a-11ea-9afd-1d58992360c7.JPG)

**Comment by wolfthefallen** [comment]
I do not see a login error on the King Phisher Server or a successful login. Confirm that the ssh server is running on the King Phisher Server, and that you can ssh to it from the command line. Then Try the client again.
