### ISSUE TITLE
Document better Postfix server configurations: Dynamic RECEIVED-BY Headers

### ISSUE THREAD

**Issue by True-Demon** [rsmusllp/king-phisher#436]
# Feature Description
This is less of a feature request than it is a helpful description for how to set up postfix in such a way that makes your king-phisher server better at evading spam filters. 

Because of how Postfix is configured, the default configuration when you set up king-phisher servers will leave a lot of problems behind for you to fix that make it difficult for your server to bypass spam filters. This is because your king-phisher server's reputation is : 

1. Not very long-lived
2. Untrusted because of its lack of mailing history
3. The domain is not aged very long
4. Your server's email headers are super janky by default

Since King-Phisher relies entirely on postfix for sending mail, we should do a better job of documenting some handy ways to fix these problems so that users have an easier time setting up phishing servers.

## Problem 1: Your Received-By header and sender domains are mismatched

Under normal mail server circumstances, when you send an email from your organization, you typically send your email via `user@totally-legit.com`, which sends an SMTP message to mail.totally-legit.com, which then relays your mail to the destination server. With King-Phisher, this flow is _totally_ different, because of the following reasons.

1. If we do not own the domain, we have no control over its DNS records (i.e. Mail spoofing / bad SPF abuse)
2. We send phishing emails from dozens of different, mismatched sender domains on the regular
3. King-Phisher significantly modifies email headers before postfix receives them
4. We are depending on deceit and being able to bypass spam filters for our campaigns to succeed.
5. We probably don't want to set up a new postfix server for each domain we send mail from cuz ... eff that.

So when King-Phisher sends email from `user@totally-legit.com` because the SPF record bad or we have control of the domain's DNS records and can whitelist ourselves, it sends successfully, but the `RECEIVED-BY` header does not match up... and the recipient gets something like this...

```
RECEIVED-BY: FROM localhost 10.0.0.8 BY king-phisher.wephishu.com  WITH ESMTP
RECEIVED-BY: FROM king-phisher.wephishu.com 1.2.3.4 BY mail.totally-legit.com 4.3.2.1  WITH ESMTP
```

First off, we just exposed our internal ip address because of the X-ORIGINATING-IP which gets dropped into this header, which isn't good OPSEC. Second, our sender domain is not matching our mailing server name. This _really_ irks certain spam filters because the sender domain (totally-legit.com) does not match the sending server. Even if the SPF record allows the mail to pass, it will elevate your spam score with certain filters enabled, depending on the service provider. 

So we need to fix two problems
1. Get postfix to present itself as having the same domain name as our sender domain.
2. Remove our IP from the first header, or get rid of the header entirely

## Solution To Problem 1:

The intent is that when you set up your client to send an email from `admin@totally-legit-domain.com`, you want the server to reflect that domain's mailing server in the Email Headers as you would expect  
(`i.e. RECEIVED-BY: FROM totally-legit.com 1.2.3.4 BY mail.totally-legit.com 4.3.2.1 WITH ESMTP`)

The trick is to set up `sender_dependent_default_transport_maps` which maps custom filter rules based on the email sender. Sender Transports allow us to modify server configurations based on the sender for both incoming/outgoing mail. We're only worried about the former, but it's a nice feature!

Here's how to do it:

### Requirements:

Add the following to /etc/postfix/master.cf:
```
totallylegit_smtp        unix    -       -       n       -       -       smtp
  -o myhostname=mail.totally-legit.com -o smtp_helo_name=totally-legit.com
```

Add the follwing to /etc/postfix/sender_transports:
```
@totally-legit.com         totallylegit_smtp:
```

Add the following to /etc/postfix/main.cf:
```
sender_dependent_default_transport_maps = hash:/etc/postfix/sender_transports
```

Load the sender_transports database table and reload postfix's config
```
#!/bin/bash
sudo postmap /etc/postfix/sender_transports
sudo postfix reload
```

### Solution to Problem 2:

By default, Postfix will put whatever is in the `$myhostname` configuration value in its Received-By header, no matter what you do. 

This is a problem because if the receiving SMTP server and the relaying/sending SMTP server do not match, then it can trip a spam filter, not to mention it exposes our hostname, so we get something like this:

```
RECEIVED-BY: FROM localhost 10.0.0.8 BY king-phisher.wephishu.com 1.2.3.4  WITH ESMTP
RECEIVED-BY: FROM totally-legit.com 1.2.3.4 BY mail.totally-legit.com 4.3.2.1  WITH ESMTP
```

Thankfully, there is an easy solution. It is common practice for SMTP servers to omit the first entry in order to protect user's anonymity because the first Received-By header always includes the X-Originating-IP and hostname of the sender, which is usually personal. Therefore, if you drop the first occurrence of the Received-By header, you can subvert this spam trigger AND protect your OPSEC at the same time.

This must be done by utilizing postfix `header_checks` which work like reg-ex based rules for how postfix treats mailing headers. You can do a _lot_ with this feature, but for now we want to stick to dropping the RECEIVED-BY header in both mime_headers and smtp_headers.

**This is what you do:**

Add the following lines to `/etc/postfix/main.cf`: 
```
header_checks = regexp:/etc/postfix/header_checks
mime_header_checks = regexp:/etc/postfix/header_checks
```

Add the following to `/etc/postfix/header_checks`
```
/^Received:.*with/      IGNORE
/^X-Originating-IP:/    IGNORE
/^X-Mailer:/            IGNORE
/^Mime-Version:/        IGNORE
```

Map the file and reload postfix:
```
sudo postmap /etc/postfix/header_checks
sudo postfix reload
```

We drop all four of these headers because we don't want to give any more information than we need to. Removing `Received:` headers will only remove the first header because it is the only one Postfix has control over.  

The X-Originating-IP header has our local address in it, which we definitely don't want to just hand over, so we drop that too.
X-Mailer is an alias for X-Originating-IP so we clear that just in case ...  

Also, we drop the Mime-Version just for good policy. Recipient servers don't use this value, as they resolve Mime-headers based on their own version anyway, and any unsupported MIME-Header content gets ignored by the server, but stays in the contents of the email header.

## Results

The result of our work is that the target ends up with a clean X-RECEIVED-BY: header that only contains
```
X-RECEIVED-BY: FROM totally-legit.com 1.2.3.4 BY mail.totally-legit.com 4.3.2.1 WITH ESMTP
```

**Comment by zeroSteiner** [comment]
I think this sounds great and I'd be happy to put it in the wiki. I'd cut the first sentence "This is less of a feature request..." and take the rest into a new page after adding a disclaimer that we don't offer Postfix support.

I would _really_ prefer to see it all re-written into the third person perspective. For example, "The result of our work is that the..." would read a bit better and be more consistent with other documentation if adjusted to "The result of these changes is that the...".

I admittedly have not checked this for technical accuracy with a live server but I trust that it is correct.
