### ISSUE TITLE
king pisher issue

### ISSUE THREAD

**Issue by madafaka221** [rsmusllp/king-phisher#438]
## Issue Description
I experience an issue when I... and the results I expected are...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Rolling Kali linux.
King Phisher Version: x.y.z

## Error Details / Stack Trace
./KingPhisherServer server_config.yml
WARNING  no pre-existing pipenv environment was found, installing it now
pipenv encountered the following error:
ERROR    failed to install the pipenv environment
ERROR    failed to remove the incomplete .venv directory
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/startup.py", line 188, in pipenv_entry
    shutil.rmtree(os.path.join(target_directory, '.venv'))
  File "/usr/lib/python3.8/shutil.py", line 706, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 704, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/king-phisher/.venv'

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
Well it looks like your virtual environment isn't installed. What happens if you run `pipenv install` from within the King Phisher directory?

**Comment by madafaka221** [comment]
good day sir.thankyou for your response..i follow your instruction and this
is happen

✘ Locking Failed!
Traceback (most recent call last):
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_vendor/urllib3/response.py",
line 425, in _error_catcher
    yield
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_vendor/urllib3/response.py",
line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_vendor/cachecontrol/filewrapper.py",
line 62, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line
807, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line
802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
parsed.write,
  File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line
785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir,
packages)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line
746, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/resolver.py", line
728, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1378,
in resolve_deps
    results, hashes, markers_lookup, resolver, skipped =
actually_resolve_deps(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 1093,
in actually_resolve_deps
    resolver.resolve()
  File "/usr/local/lib/python3.8/dist-packages/pipenv/utils.py", line 808,
in resolve
    results =
self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/piptools/resolver.py",
line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/piptools/resolver.py",
line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/piptools/resolver.py",
line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/piptools/repositories/pypi.py",
line 226, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/piptools/repositories/pypi.py",
line 347, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/piptools/repositories/pypi.py",
line 303, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/legacy_resolve.py",
line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/legacy_resolve.py",
line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py",
line 473, in prepare_linked_requirement
    local_path = unpack_url(
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py",
line 282, in unpack_url
    return unpack_http_url(
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py",
line 158, in unpack_http_url
    from_path, content_type = _download_http_url(
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py",
line 303, in _download_http_url
    for chunk in download.chunks:
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_internal/network/utils.py",
line 15, in response_chunks
    for chunk in response.raw.stream(
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_vendor/urllib3/response.py",
line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_vendor/urllib3/response.py",
line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File
"/usr/local/lib/python3.8/dist-packages/pipenv/patched/notpip/_vendor/urllib3/response.py",
line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError:
HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed
out.

**Comment by zeroSteiner** [comment]
It's showing that it can't connect to download the necessary files. Are you behind some kind of proxy or otherwise disconnected from the internet?

**Comment by madafaka221** [comment]
thank you for your response again sir im connected connected to on internet
sir..

**Comment by madafaka221** [comment]
good day sir thankyou for your response. im connected to the internet sir

**Comment by zeroSteiner** [comment]
> pipenv.patched.notpip._vendor.urllib3.exceptions.ReadTimeoutError:
> HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out

Well this error implies that something is wrong with your connection since it can't connect to https://files.pythonhosted.org/.  You'll need to fix that to install the necessary dependencies.

**Comment by madafaka221** [comment]
thank you sir god bless

**Comment by madafaka221** [comment]
i have another problem.  pipenv install
Creating a virtualenv for this project…
Pipfile: /opt/king-phisher/Pipfile
Using /usr/bin/python3 (3.8.5) to create virtualenv…
⠇ Creating virtual environment...created virtual environment CPython3.8.5.final.0-64 in 2714ms
  creator CPython3Posix(dest=/home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz, clear=False, global=False)
  seeder FromAppData(download=False, msgpack=latest, colorama=latest, CacheControl=latest, retrying=latest, pep517=latest, distro=latest, packaging=latest, ipaddr=latest, setuptools=latest, pytoml=latest, contextlib2=latest, pip=latest, six=latest, pkg_resources=latest, requests=latest, wheel=latest, idna=latest, html5lib=latest, distlib=latest, certifi=latest, urllib3=latest, chardet=latest, appdirs=latest, webencodings=latest, lockfile=latest, progress=latest, pyparsing=latest, via=copy, app_data_dir=/home/nannek/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz
Installing dependencies from Pipfile.lock (b2bec2)…
An error occurred while installing https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz#egg=basemap --hash=sha256:3fb30424f18cd4ffd505e30fd9c810ae81b999bb92f950c76553e1abc081faa7! Will try again.
An error occurred while installing pyproj==2.4.0 --hash=sha256:4a26485f09052722deaa1ddc6b3133d41bd982be5b0e64e296626e71b94ee5e6 --hash=sha256:36ad4ff82f38cdc7738da81289ec4309263ad40f3d62cb75eeef22bb70178698 --hash=sha256:8e2a8fab431bc6d16a417792198813fe6b8c53aafb51f54e1e6a52cdb377b576 --hash=sha256:fb151507b8793acc8c622164e3cc57d0c51f3d4790dabba1daf141a780bad68a --hash=sha256:5d1f4f2645abd05128d29bd71eb378ff0fedb9f96147356e68b87a628863bf92 --hash=sha256:4b41db92d689119b57ff6fcc3ae5a75072c86a7078cb0c25434b3ab4b79ad624 --hash=sha256:0f3b3280ae59c74212841c38d1df055537b4e83cbfcda4072ba6b0eeefd0b98a --hash=sha256:a8462505b4fa7e7e73ac5e69f1aa3d4a31b25e93dac80a41a2ff35d996c3f173 --hash=sha256:c22c52ea26d318d808bdde23e2b57b85c292747971ff79d0ea578b578ff791d6 --hash=sha256:9121e2ae3eb13d32cf2c49e456e052fe88cab200cfc07e3162cdb276427040fa --hash=sha256:d25638d48af3df03c6d3c713495d62d0b9a135032b0dddafbb7f0004d052b1f5 --hash=sha256:7c05ca74d7a3c822afd933e2efb5c599475c1cb22919500cb7df8ecb1c24d04e --hash=sha256:8124fe43d81a7caca43df6930110e2bfd2bd3b82b86587eefd6f6d86a81a658e --hash=sha256:d851dd9245f60871306a49af92523a8ea8d8a60f3e522bbd8b9cd512d8b825ec --hash=sha256:e27a5bec46c706a343db9b218bf13abd53f1e066668b194bd48511c1773f6c1c! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 65/65 — 00:08:47
Installing initially failed dependencies…
[InstallError]:   File "/home/nannek/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 232, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/home/nannek/.local/lib/python3.8/site-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/home/nannek/.local/lib/python3.8/site-packages/pipenv/core.py", line 1305, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/home/nannek/.local/lib/python3.8/site-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/home/nannek/.local/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/home/nannek/.local/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting pyproj==2.4.0
[pipenv.exceptions.InstallError]:   Using cached pyproj-2.4.0.tar.gz (460 kB)
[pipenv.exceptions.InstallError]: Building wheels for collected packages: pyproj
[pipenv.exceptions.InstallError]:   Building wheel for pyproj (setup.py): started
[pipenv.exceptions.InstallError]:   Building wheel for pyproj (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]:   ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z5j4wi3p/pyproj/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z5j4wi3p/pyproj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4txjbgd8
[pipenv.exceptions.InstallError]:        cwd: /tmp/pip-install-z5j4wi3p/pyproj/
[pipenv.exceptions.InstallError]:   Complete output (31 lines):
[pipenv.exceptions.InstallError]:   running bdist_wheel
[pipenv.exceptions.InstallError]:   running build
[pipenv.exceptions.InstallError]:   running build_py
[pipenv.exceptions.InstallError]:   creating build
[pipenv.exceptions.InstallError]:   creating build/lib.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:   creating build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/__main__.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/geod.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/proj.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/compat.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/enums.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/utils.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/_show_versions.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/transformer.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/datadir.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/cf1x8.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/exceptions.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/__init__.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   copying pyproj/crs.py -> build/lib.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   warning: build_py: byte-compiling is disabled, skipping.
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   running build_ext
[pipenv.exceptions.InstallError]:   building 'pyproj._proj' extension
[pipenv.exceptions.InstallError]:   creating build/temp.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:   creating build/temp.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:   x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/include -I/usr/include/python3.8 -c pyproj/_proj.c -o build/temp.linux-x86_64-3.8/pyproj/_proj.o
[pipenv.exceptions.InstallError]:   pyproj/_proj.c:623:10: fatal error: proj.h: No such file or directory
[pipenv.exceptions.InstallError]:     623 | #include "proj.h"
[pipenv.exceptions.InstallError]:         |          ^~~~~~~~
[pipenv.exceptions.InstallError]:   compilation terminated.
[pipenv.exceptions.InstallError]:   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
[pipenv.exceptions.InstallError]:   ----------------------------------------
[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for pyproj
[pipenv.exceptions.InstallError]:   Running setup.py clean for pyproj
[pipenv.exceptions.InstallError]: Failed to build pyproj
[pipenv.exceptions.InstallError]: Installing collected packages: pyproj
[pipenv.exceptions.InstallError]:     Running setup.py install for pyproj: started
[pipenv.exceptions.InstallError]:     Running setup.py install for pyproj: finished with status 'error'
[pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:      command: /home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z5j4wi3p/pyproj/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z5j4wi3p/pyproj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cztp7bdw/install-record.txt --single-version-externally-managed --compile --install-headers /home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/include/site/python3.8/pyproj
[pipenv.exceptions.InstallError]:          cwd: /tmp/pip-install-z5j4wi3p/pyproj/
[pipenv.exceptions.InstallError]:     Complete output (15 lines):
[pipenv.exceptions.InstallError]:     running install
[pipenv.exceptions.InstallError]:     running build
[pipenv.exceptions.InstallError]:     running build_py
[pipenv.exceptions.InstallError]:     warning: build_py: byte-compiling is disabled, skipping.
[pipenv.exceptions.InstallError]:     
[pipenv.exceptions.InstallError]:     running build_ext
[pipenv.exceptions.InstallError]:     building 'pyproj._proj' extension
[pipenv.exceptions.InstallError]:     creating build/temp.linux-x86_64-3.8
[pipenv.exceptions.InstallError]:     creating build/temp.linux-x86_64-3.8/pyproj
[pipenv.exceptions.InstallError]:     x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/include -I/usr/include/python3.8 -c pyproj/_proj.c -o build/temp.linux-x86_64-3.8/pyproj/_proj.o
[pipenv.exceptions.InstallError]:     pyproj/_proj.c:623:10: fatal error: proj.h: No such file or directory
[pipenv.exceptions.InstallError]:       623 | #include "proj.h"
[pipenv.exceptions.InstallError]:           |          ^~~~~~~~
[pipenv.exceptions.InstallError]:     compilation terminated.
[pipenv.exceptions.InstallError]:     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
[pipenv.exceptions.InstallError]:     ----------------------------------------
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: /home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z5j4wi3p/pyproj/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z5j4wi3p/pyproj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cztp7bdw/install-record.txt --single-version-externally-managed --compile --install-headers /home/nannek/.local/share/virtualenvs/king-phisher-RbupqVtz/include/site/python3.8/pyproj Check the logs for full command output.
ERROR: Couldn't install package: pyproj
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/2 — 00

**Comment by True-Demon** [comment]
It looks like you are missing linux headers and probably python-dev as well.

Run the following command:
`sudo apt install build-essential linux-headers-$(uname -r) python3-dev`

Then try running pipenv install again.

**Comment by CryptoShoe** [comment]
Hi there I am having issues installing king-phisher on my kali linux vm. I have followed a few different guides now and I have run into this issue after finding the securestate installation guide. I cant seem to launch king-phisher as it says its missing .venv files and pipenv. I have tried to fix the pipenv issue but no luck. Someone please help! 

![KingPhisherhelp](https://user-images.githubusercontent.com/77485517/194468262-3c623d56-981a-45c3-b4f7-377ee079388a.PNG)

**Comment by hwac121** [comment]
Regardless of following all the advice here I still get errors trying to run King Phisher. 

---- BEGIN ERROR -----
./KingPhisher
WARNING  no pre-existing pipenv environment was found, installing it now
pipenv encountered the following error:
ERROR    failed to install the pipenv environment
----- END ERROR ------

Is pipenv installed? YES, it is installed correctly

I used to LOVE this app but right now it is unusable...

**Comment by FaizanBhait** [comment]
> It looks like you are missing linux headers and probably python-dev as well.
> 
> Run the following command: `sudo apt install build-essential linux-headers-$(uname -r) python3-dev`
> 
> Then try running pipenv install again.

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-4.9.117
E: Couldn't find any package by glob 'linux-headers-4.9.117'

**Comment by FaizanBhait** [comment]
Anyone please help

**Comment by hamzarana07** [comment]
@FaizanBhait Hi, I have the same kernel, 4.9.117+.
Were you able to fix this issue? If yes, please tell me how. I've been doing so much for this to install, but whatever I do, it's useless at the end of the day.
