### ISSUE TITLE
Campaign Overview Not Reflecting Opened/Visits

### ISSUE THREAD

**Issue by NAngryPole** [rsmusllp/king-phisher#439]
## Issue Description
Sent out 2 emails to my personal account to do some testing with SPAM Filtering. I sent Calendar invites and when i click on Join Meeting i go back to the server refresh the overview and see the messages total changes but Opened and visits do not.

What am i missing?

## Reproduction Steps
1. Start King Phisher
2. Send Calendar invite email 
3. Open invite email as target
4. Open overview on server view the stats

## Environment Details

Host OS: Kali 2019.3
King Phisher Version: 1.15.0

**Comment by zeroSteiner** [comment]
You're probably missing the UID in the webserver URL.

**Comment by Quiark** [comment]
same problem here and I'm NOT missing the uid in the URL
