### ISSUE TITLE
python3 -m pip install -r requirements.txt error

### ISSUE THREAD

**Issue by librahimli** [rsmusllp/king-phisher#440]
Hello geniuses, 
When I tried this command :
python3 -m pip install -r requirements.txt 
It gives me the following error :
ERROR: could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' 
Any solutions to this ? 
Thanks a lot..

**Comment by wolfthefallen** [comment]
King Phisher utilizes `pipenv` to create its own python3 enviroment to run. You can use `tools/install.sh` to install all the requirements for King Phisher and its `pipenv` environment.
