### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by Kuandt** [rsmusllp/king-phisher#442]
## Issue Description
I experience an issue when I try to log in. The results I expected are that i get in smoothly. 

I am trying to log in. As far as i understood, the credentials that one uses to login are what one uses to log into their computer. Am I wrong?

**Comment by wolfthefallen** [comment]
@Kuandt Kuandt, you are correct it is the credentials you utilize to ssh/login into the King Phisher Server.

https://github.com/rsmusllp/king-phisher/wiki/Frequently-Asked-Questions#what-are-the-default-credentials
