### ISSUE TITLE
Cannot start KingPhisherServer service; ModuleNotFoundError: No module named 'termcolor'

### ISSUE THREAD

**Issue by RedLectroid** [rsmusllp/king-phisher#443]
## Issue Description
I experience an issue when I attempt to start the kingphisher service after installation.

## Reproduction Steps
1. sudo apt update && apt upgrade
2. git clone https://github.com/rsmusllp/king-phisher.git
3. sudo tool/install.sh -y --skip-client

## Environment Details
Host OS: Fresh AWS VPS of Ubuntu Server 18.04 64bit

## Error Details / Stack Trace
The service will not start.  The error it is displaying indicates that the modules required by the python scripts are not getting installed.  I can manually install them one at a time using pipenv install to get rid of the errors one by one, but it does not solve the problem.

```
✔ Successfully created virtual environment! 
Virtualenv location: /opt/king-phisher/.venv
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
⠏ Locking..✔ Success! 
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
⠙ Locking..✘ Locking Failed! 

Job for king-phisher.service failed because the control process exited with error code.
See "systemctl status king-phisher.service" and "journalctl -xe" for details.

● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-10-07 00:14:16 UTC; 7min ago
  Process: 17912 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=1/FAILURE)

Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:     exec(code, run_globals)
Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:   File "/opt/king-phisher/king_phisher/server/__main__.py", line 42, in <module>
Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:     from king_phisher import color
Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:   File "/opt/king-phisher/king_phisher/color.py", line 41, in <module>
Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:     import termcolor
Oct 07 00:14:16 ip-172-31-13-182 python3[17912]: ModuleNotFoundError: No module named 'termcolor'
Oct 07 00:14:16 ip-172-31-13-182 systemd[1]: king-phisher.service: Control process exited, code=exited status=1
Oct 07 00:14:16 ip-172-31-13-182 systemd[1]: king-phisher.service: Failed with result 'exit-code'.
Oct 07 00:14:16 ip-172-31-13-182 systemd[1]: Failed to start King Phisher Server.

```

**Comment by wolfthefallen** [comment]
`pipenv` is failing to create a `Pipfile.lock` file or update it.
User is currently using aws `ubuntu 18.04` instance `python 3.6.9`
user ran `export PIPENV_VENV_IN_PROJECT=True && pipenv --verbose --site-packages install`
output: https://pastebin.com/BvFz1j6z

output did not say what package is causing a lock failure or at least what I could find.
Had the user use a `Pipefile.lock` file from an aws instance running the same (I could not recreate the issue) and it failed to accept nor update the file.
user is running `pipenv, version 2020.8.13`

**Comment by hwac121** [comment]
> ## Issue Description
> I experience an issue when I attempt to start the kingphisher service after installation.
> 
> ## Reproduction Steps
> 1. sudo apt update && apt upgrade
> 2. git clone https://github.com/rsmusllp/king-phisher.git
> 3. sudo tool/install.sh -y --skip-client
> 
> ## Environment Details
> Host OS: Fresh AWS VPS of Ubuntu Server 18.04 64bit
> 
> ## Error Details / Stack Trace
> The service will not start. The error it is displaying indicates that the modules required by the python scripts are not getting installed. I can manually install them one at a time using pipenv install to get rid of the errors one by one, but it does not solve the problem.
> 
> ```
> ✔ Successfully created virtual environment! 
> Virtualenv location: /opt/king-phisher/.venv
> Pipfile.lock not found, creating…
> Locking [dev-packages] dependencies…
> Building requirements...
> Resolving dependencies...
> ⠏ Locking..✔ Success! 
> Locking [packages] dependencies…
> Building requirements...
> Resolving dependencies...
> ⠙ Locking..✘ Locking Failed! 
> 
> Job for king-phisher.service failed because the control process exited with error code.
> See "systemctl status king-phisher.service" and "journalctl -xe" for details.
> 
> ● king-phisher.service - King Phisher Server
>    Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2020-10-07 00:14:16 UTC; 7min ago
>   Process: 17912 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=1/FAILURE)
> 
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:     exec(code, run_globals)
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:   File "/opt/king-phisher/king_phisher/server/__main__.py", line 42, in <module>
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:     from king_phisher import color
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:   File "/opt/king-phisher/king_phisher/color.py", line 41, in <module>
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]:     import termcolor
> Oct 07 00:14:16 ip-172-31-13-182 python3[17912]: ModuleNotFoundError: No module named 'termcolor'
> Oct 07 00:14:16 ip-172-31-13-182 systemd[1]: king-phisher.service: Control process exited, code=exited status=1
> Oct 07 00:14:16 ip-172-31-13-182 systemd[1]: king-phisher.service: Failed with result 'exit-code'.
> Oct 07 00:14:16 ip-172-31-13-182 systemd[1]: Failed to start King Phisher Server.
> ```

Did you make sure to point it to the config file? Is the config file configured properly?

**Comment by wolfthefallen** [comment]
@hwac121 config file is not the issue, pipenv is failing to create `Pipefile.lock` file. 
@RedLectroid did confirm today that he successfully installed King Phisher on a Digital Ocean Ubuntu 18.04 droplet, narrowing down the issue to the free level AWS EC2 instance.

**Comment by zeroSteiner** [comment]
Since you're using the free tier, I'm pretty confident that you simply lack the RAM to install all of the dependencies. I did some digging into this scenario with Digital Ocean and these were the results.

|              | $5/mo      | $40/mo     |
| ------------ | ---------- | ---------- |
| Ubuntu 18.04 | successful | successful | 
| Ubuntu 20.04 | **failed** | successful |

In all 4 cases, I installed no software, I just logged in a root, cloned the repo and ran the installer with `tools/install.sh --skip-client --yes`. Unfortunately there's a lot of dependencies for a project this size so you need a bit more power to install them all. You may be able to downsize once the installation has completed.

**Comment by RedLectroid** [comment]
Can confirm:  free tier has insufficient resources for the install.  Will close the Issue.  Appreciate the help!!
