### ISSUE TITLE
Error Launching King Phisher von Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by semahler** [rsmusllp/king-phisher#444]
## Issue Description
I tried to install King Phisher on Ubuntu 16.04 LTS within VirtualBox. The OS is nearly stock and only with marginal changes an configurations. Firstly, the installation of server and client runs correctly with the provided installation script. But when I afterwards tried to run King Phisher, I got an error from Python library, that a module called 'gi' was not found and therefore could not imported.
I researched a lot in different sources and websites about the error but all the tips and solution proposal didn't work for me.

## Reproduction Steps
1. Install Ubuntu 16.04 LTS within VirtualBox
2. Install Guest Additions
3. Update/upgrade distribution
4. Download and run the installation script provided in the documentation
5. Try to start King Phisher

## Environment Details
Host OS: Ubuntu 16.04 LTS GNOME within VirtualBox with installed Guest Additions
King Phisher Version: Latest provided in the repository

## Error Details / Stack Trace
<img width="1087" alt="error_king_phisher" src="https://user-images.githubusercontent.com/38438841/96328663-e2df3980-1045-11eb-8f2f-c5221161a63b.png">

**Comment by zeroSteiner** [comment]
Well we don't support 16.04 any more. That's a 4 year old distro and we don't have the resources to support as many as we'd like. Try again using 20.04.
