### ISSUE TITLE
Warning matplotlib is not installed, dashboard will not be available

### ISSUE THREAD

**Issue by geekypanda411** [rsmusllp/king-phisher#449]
## Issue Description
Reinstalled King-Phisher from repo in Kali (2020), Started King-Phisher service and then client. Client starts up fine but gives the above warning. Tried to install matplotlib with pip3 and apt-get installed successfully but still does not reflect with the client.

## Reproduction Steps
1. Start King Phisher Client
2. Gives out this warning

## Environment Details

Host OS: Kali 2 (2020-07-01) 
King Phisher Version: 1.16.0-beta

## Error Details / Stack Trace

```
WARNING it is not necessary to run the king phisher client as root
WARNING matplotlib is not installed, dashboard will not be available
```

**Comment by zeroSteiner** [comment]
Well if you installed a package through the Kali package repository and there's a missing dependency, then that sounds like an issue you'd need to raise with the Kali team that distributes that package.

If you installed King Phishre through git, then you'd need to install matplotlib using `pipenv` from within the directory you installed King Phisher.

**Comment by geekypanda411** [comment]
Ok, I will reach out to their team. Thanks for the help.

**Comment by qwertyuiop-7766** [comment]
How did you fix this? @geekypanda411

**Comment by geekypanda411** [comment]
> How did you fix this? @geekypanda411 

Did not actually, Seems like an issue with kali(as they mentioned) that's why I closed the issue here.
