### ISSUE TITLE
Problem starting KingPhisher Server

### ISSUE THREAD

**Issue by Pyth18** [rsmusllp/king-phisher#453]
When I start King Phisher when inserting my credentials I get a message like this: "The server refused the connection". I have started the SSH server, as you can see below: 

<img width="473" alt="Captura1" src="https://user-images.githubusercontent.com/74792993/103841147-8bef6c00-5058-11eb-80d2-2976ad5a307c.PNG">

But when I try to run the KingFisher server I get the following critical error:
<img width="631" alt="Captura2" src="https://user-images.githubusercontent.com/74792993/103841588-89d9dd00-5059-11eb-95aa-bd3ce868638c.PNG">

This is the process information:
<img width="919" alt="Captura3" src="https://user-images.githubusercontent.com/74792993/103841760-f3f28200-5059-11eb-8fd2-3d3b7a0d591d.PNG">

I have gone through some strings prior to problems, similar with queries to the database, but I can't resolve this one. Thank you for your answer!

**Comment by wolfthefallen** [comment]
@Pyth18 The issue is the password for the postgres user for the database in the server config file is not the correct password.

Option 1) You will need to change the password for that database user and then update your server config. 

The link below has a link to the postgres section that will help you complete this task.

https://github.com/rsmusllp/king-phisher/wiki/Frequently-Asked-Questions#database-authentication-failure

**Comment by Pyth18** [comment]
Hello! I have already changed the postgresql credentials, but it has given me a problem with the geoip database, however I also solved that problem by downloading another database and changing the path in the king phisher server configuration. But now it gives me this problem, it helps, I feel that I will not be able to have this tool on my computer:

<img width="816" alt="Captura1" src="https://user-images.githubusercontent.com/74792993/103954502-fdd3be00-5109-11eb-8db6-da13ff5d51b8.PNG">

**Comment by wolfthefallen** [comment]
from the `king-phisher` directory please run `./KingPhisherServer -f -L DEBUG server_config.yml` and please provide the detailed output.
