### ISSUE TITLE
Client does not start on WSL/Ubuntu18.04

### ISSUE THREAD

**Issue by turilaszlo** [rsmusllp/king-phisher#454]
## Issue Description
The client cannot be started. 

## Reproduction Steps
1. KingPhisher installed sucessfully on Ubuntu18.04 under WSL2
2. Powershell started.
3. Ubuntu started with 'bash' command.
4. cd /opt/king-phisher/
5. ./King-Phisher

## Environment Details
Host OS: Ubuntu 18.04 Server under Windows 2019 server WSL2
Xserver: Xming
King Phisher Version: 1.15.0

## Error Details / Stack Trace
Loading .env environment variables...
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
   File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
   File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
   File "/opt/king-phisher/king_phisher/client/__init__.py", line 35, in <module>
     import gi
 ModuleNotFoundError: No module named 'gi'

**Comment by turilaszlo** [comment]
This did not help. After running install.sh and restart WSL the same error message appears and client does not start.

**Comment by wolfthefallen** [comment]
verify the following items are installed through apt-get `gir1.2-gtk-3.0 gir1.2-gtksource-3.0 python3-cairo libgeos++-dev libgirepository1.0-dev libgtk-3-dev libpq-dev python3-gi python3-gi-cairo libpq-dev` ..

If they are all installed, navigate to your `king-phisher` folder then `sudo su` then run `export PIPENV_VENV_IN_PROJECT=True && pipenv --site-packages install`
