### ISSUE TITLE
KingPhisher.exe does not start

### ISSUE THREAD

**Issue by turilaszlo** [rsmusllp/king-phisher#455]
## Issue Description
KingPhisher.exe (the Windows client application) cannot be launched. The error message refers to a Visual C++ file not listed as prerequisite. Reinstallation does not help.

## Reproduction Steps
1. Download the latest Windows build of KingPhisher
2. Install it on Windows 2019.
3. Click KingPhisher icon in Start menu.

## Environment Details
Host OS: Windows Server 2019 Datacenter, ver. 1809, OS build 17763.1637
King Phisher Version: 1.15.0

## Error Details / Stack Trace
"KingPhisher.exe - System error: The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem."
![Installed-apps](https://user-images.githubusercontent.com/46007001/104358549-e5e7aa00-550e-11eb-8fb2-af24d93daf86.JPG)
![KingPhisher exe cannot start](https://user-images.githubusercontent.com/46007001/104358552-e718d700-550e-11eb-8974-b4103a2c069d.JPG)
![environment](https://user-images.githubusercontent.com/46007001/104358553-e718d700-550e-11eb-9fe4-2efaf84a043b.JPG)

**Comment by wolfthefallen** [comment]
This is a duplicate of issue #445. Unfortunately, the King Phisher project is no longer supporting windows build. You can utilize WSL if you need to run on a windows system. https://github.com/rsmusllp/king-phisher/blob/2181ba508d5fa3fc2517cbedc459e536ecc7b22e/INSTALL.md#windows-10-subsystem-for-linux-wsl

**Comment by zeroSteiner** [comment]
I want to add that it looks like there was a solution [posted](https://github.com/rsmusllp/king-phisher/issues/445#issuecomment-713732176) for the related issue:

> Works after install of Microsoft Visual C++ 2010 Redistributable Package (x86) - https://www.microsoft.com/en-us/download/details.aspx?id=5555

But yeah, we're aware of this and won't be fixing it for the reasons outlined in that ticket.

**Comment by turilaszlo** [comment]
@zeroSteiner The old solution of #445 still works. Thank you.
