### ISSUE TITLE
I create plugin for tracking functionality to the attachment sent by King-phisher

### ISSUE THREAD

**Issue by samira-karimi-elfiman** [rsmusllp/king-phisher#457]
Hello
Thank you for your excellent tool and I really enjoyed working with it
I needed to automatically generate a word attachment that includes the unique user id. I had to send the created attachments to each user. The idea was to be able to track users who open attachments. So I designed a plugin and I'm interested in sharing it with others. I hope it will be accepted by you and will be included in your list of plugins

How can I send you the code file?
 
Thank you very much

**Comment by zeroSteiner** [comment]
Hey that's great! We accept new plugins submitted as PRs to the [king-phisher-plugins](https://github.com/rsmusllp/king-phisher-plugins) repository. You'll need to fork the repo, and submit a PR from a topic branch to add your files.

Some common mistakes to watch out for:

- Please follow our [documented style guide](https://king-phisher.readthedocs.io/en/latest/development/style_guide.html)
- Please include very clear and detailed testing steps that demonstrate the functionality that you've added
- Make sure to fill out all of the plugin metadata fields

Once you've done that we'll take a look at the code and test it! If you have any questions, the best thing to do would be to open the PR and ask them in the PR so we can see the code which will provide helpful context when answering.

**Comment by samira-karimi-elfiman** [comment]
Hello
I will definitely do what you said in the next two days
thank you for your guidance

**Comment by MDR41** [comment]
love

**Comment by wolfthefallen** [comment]
The PR for this issue is:
https://github.com/rsmusllp/king-phisher-plugins/pull/42
