### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by or552244** [rsmusllp/king-phisher#466]
## Issue Description
I experience an issue when I try to write an email with Hebrew in it.

## Reproduction Steps
1. Start King Phisher
2. write in Hebrew  in the html tags

## Environment Details

Host OS: 4.4.0-1127-aws #141-Ubuntu SMP Tue Apr 13 14:07:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (server) Windows 10 pro build 19042 (client)
King Phisher Version:1.15.0

## Error Details / Stack Trace
Error Type: builtins.UnicodeEncodeError
Error Details: UnicodeEncodeError('charmap', '<html>\r\n<head>\r\n</head>\r\n<body>\r\n<h1>בדיקה</h1>\r\n</body>\r\n</html>', 37, 42, 'character maps to <undefined>')
Error UID: f7165621-998b-4064-b6ba-57ad4f6f117a
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.15.0
Platform Version: Windows: 10 10.0.19041  Multiprocessor Free (Frozen=True)
Python Version: 3.4.4
Gtk Version: 3.18.9
Timezone: Asia/Jerusalem

Thread Information:
===================
    Thread-13 (alive=True daemon=False)
    ServerEventsDispatcher (alive=True daemon=True)
    Thread-14 (alive=True daemon=True)
    Thread-18 (alive=True daemon=True)
 => MainThread (alive=True daemon=False)
    RPCAsyncWorker (alive=True daemon=False)

Stack Trace:
============
Traceback (most recent call last):
  File "C:\Program Files (x86)\Jenkins\workspace\king-phisher-master\king_phisher\client\tabs\mail.py", line 1270, in signal_notebook_switch_page
  File "C:\Program Files (x86)\Jenkins\workspace\king-phisher-master\king_phisher\client\tabs\mail.py", line 688, in save_html_file
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-41: character maps to <undefined>

**Comment by zeroSteiner** [comment]
Try using an external editor like Notepad++ to write your content and make sure to save it as UTF-8. The content all needs to be UTF-8 encoded. There's not much else we can do about this error and it looks like you're using the Windows build which we're no longer updating.

**Comment by or552244** [comment]
thank you for the quick answer.
I tried to convert it before with notepad++ but now it works for some reason.
and I'll use my Kali Linux as the client.
