### ISSUE TITLE
Critical server 

### ISSUE THREAD

**Issue by crian92** [rsmusllp/king-phisher#467]
## Issue Description
I experience an issue saying critical server failed while I'm trying to run this command. /KingPhisherServer server_config yml

## Environment Details

Kali 2020

## Error Details / Stack 
![20210507_133622](https://user-images.githubusercontent.com/83835389/117488155-10d09080-af3a-11eb-9669-7e9d51dc943a.jpg)

If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
It says the database initialization failed. You should double check the connection string and make sure that the password is correct and postgresql is running.

**Comment by crian92** [comment]
> It says the database initialization failed. You should double check the connection string and make sure that the password is correct and postgresql is running.



> It says the database initialization failed. You should double check the connection string and make sure that the password is correct and postgresql is running.

Is there a way you can walk me thru this?

**Comment by crian92** [comment]
The password that I been using is the one that I log in into kali and it keeps saying failed to connect

**Comment by crian92** [comment]
When I try to log in into king-phisher using my kali log in username, it keeps saying unable to connect

**Comment by crian92** [comment]
From what I can see my postgresql is running

![20210507_135434](https://user-images.githubusercontent.com/83835389/117521762-78f49600-af7d-11eb-9435-900a026c156a.jpg)

**Comment by crian92** [comment]
My postgreSQL is working, idk what can be wrong


> It says the database initialization failed. You should double check the connection string and make sure that the password is correct and postgresql is running.

![Uploading 16204384088192797367555867391042.jpg…]()
