### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [rsmusllp/king-phisher#470]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine README.md, king_phisher/client/gui_utilities.py and observe `seperate`, however expect to see `separate`.
- Examine king_phisher/server/pylibc.py and observe `passwrd`, however expect to see `password`.
- Examine docs/source/king_phisher/server/graphql/middleware.rst and observe `middlware`, however expect to see `middleware`.
- Examine king_phisher/client/export.py and observe `workseet`, however expect to see `worksheet`.
- Examine king_phisher/client/gui_utilities.py and observe `styeled`, however expect to see `styled`.
- Examine king_phisher/client/widget/extras.py and observe `renderering`, however expect to see `rendering`.
- Examine docs/source/development/windows_build.rst and observe `ouput`, however expect to see `output`.
- Examine king_phisher/utilities.py and observe `mininum`, however expect to see `minimum`.
- Examine king_phisher/client/mailer.py and observe `messsages`, however expect to see `messages`.
- Examine king_phisher/sms.py and observe `messsage`, however expect to see `message`.
- Examine tools/development/cx_freeze.py and observe `executible`, however expect to see `executable`.
- Examine king_phisher/client/widget/extras.py and observe `choosen`, however expect to see `chosen`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/king-phisher/pull/new/bugfix_typos

Thanks.

**Comment by zeroSteiner** [comment]
Thanks alot!
