### ISSUE TITLE
How can i Stop my king-phisher-server client and unreserve my port 22

### ISSUE THREAD

**Issue by ayushkmr2009** [rsmusllp/king-phisher#480]
## Issue Description
please help me i after a run king phisher server my local port 22 was reserved i think when i will reboot my pc it will be freed but its not getting free and i am unable to stop ssh 22/tcp HOW CAN STOP KING PHISHER SERVER
btw, i used this command to start the server :
```
cd /etc/king-phisher &&
king-phisher-server server_config.yml &
THEN I RUN KING-PHISHER FROM APPLICATION MENU
```

## Environment Details

Host OS: Linux kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux
King Phisher Version: 1.16.0-beta

## Real Problem
so after all explaination the main issue is that ***how can i stop the server and make my _port 22_ free***

**Comment by ayushkmr2009** [comment]
> ## Issue Description
> 
> please help me i after a run king phisher server my local port 22 was reserved i think when i will reboot my pc it will be freed but its not getting free and i am unable to stop ssh 22/tcp HOW CAN STOP KING PHISHER CLIENT btw, i used this command to start the server -=>``` cd /etc/king-phisher 
                                      king-phisher-server server_config.yml &```
> 
> 
>              THEN I RUN KING-PHISHER FROM APPLICATION MENU
> 
> ## Reproduction Steps
> 1. Start King Phisher
> 2. Do something to trigger the crash
> 
> ## Environment Details
> 
> Host OS: Linux kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux
> King Phisher Version: 1.16.0-beta
> 
> ## Error Details / Stack Trace
> 
> ```
> 
> If you are opening an issue regarding the client, copy text from the "Error Details" of the error dialog in the client here. If you are opening an issue regarding the server copy the relevant lines from the logs here.

**Comment by ayushkmr2009** [comment]
HELP ME PLEASE

**Comment by wolfthefallen** [comment]
King phisher server should only be binding to port 80 by default. 22 by default is used for sshd .. not sure why you are having it bind to port 22. Please reference the FAQ (https://github.com/rsmusllp/king-phisher/wiki/Frequently-Asked-Questions) and the How to videos (https://github.com/rsmusllp/king-phisher/wiki/Videos#how-to-videos).

**Comment by ayushkmr2009** [comment]
sir can u help me in knowing that how can i stop it

**Comment by ayushkmr2009** [comment]
OOOOOOOOO sir finally i stopped my port
now i can close this issue

**Comment by mie0812** [comment]
P,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
